- name: install knative
  hosts: localhost
  tasks:
  - name: install custom resources
    kubernetes.core.k8s:
      state: present
      remote_src: https://github.com/knative/serving/releases/download/knative-v1.16.0/serving-crds.yaml
  - name: install core components
    kubernetes.core.k8s:
      state: present
      remote_src: https://github.com/knative/serving/releases/download/knative-v1.16.0/serving-core.yaml
  - name: download helm
    ansible.builtin.command: curl -o /tmp/installhelm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    args:
      creates: /tmp/installhelm.sh
  - name: install helm
    ansible.builtin.command: bash /tmp/installhelm.sh
    args:
      creates: /usr/local/bin/helm
  - name: change permissions on helm
    become: true
    ansible.builtin.file:
      path: /usr/local/bin/helm
      mode: o=x  
  - name: Add kong chart repo
    kubernetes.core.helm_repository:
      name: kong
      repo_url: "https://charts.konghq.com"
  - name: create namespace kong-external
    kubernetes.core.k8s:
      name: kong-external
      api_version: v1
      kind: Namespace
      state: present
  - name: install kong-external
    kubernetes.core.helm:
      name: kong-external
      chart_ref: kong/kong
      release_namespace: kong-external
  - name: create namespace kong-internal
    kubernetes.core.k8s:
      name: kong-internal
      api_version: v1
      kind: Namespace
      state: present
  - name: install kong-internal
    kubernetes.core.helm:
      name: kong-internal
      chart_ref: kong/kong
      release_namespace: kong-internal
      values:
        "--set proxy.type": "ClusterIP"
        "--set ingressController.ingressClass": "kong-internal"
